const { initConnection, getDb } = require('./src/database/connection');
const crypto = require('crypto');

async function runImport() {
    await initConnection();
    const db = getDb();

const rawList = `Harina pan 
Harina santoni
Harina belen 
Harina mary
Harina Yaracuy

Arroz agua blanca 
ARROZ SANTONY
ARROZ KALY
ARROZ MASIA
ARROZ MONICA
Pasta de kilo corta
Pasta de kilo larga 
PASTA MEDIO C
PASTTA MEDIO L
OTRAS
OTRAS
Azucar kilo
AZUCAR MEDIO
AZUCAR 1/4
CAFE BRASIL 100GR
CAFE BRASIL 200GR
CAFE AMANECER 100GR
CAFE AMANECER 200GR
CAFE ALVARIGUA 100GR
CAFE ALVARIGUA 200GR
CAFE FAVORITO 50GR
CAFE FAVORITO 100GR
CAFE FAVORITO 200GR
CAFE ARAUCA 100GR
CAFE ARAUCA50GR
CAFE SELLO R
CAFE DELA NONA 100GR
CAFE MANNER 100GR
CAFE AURORA 100GR
Cafe aurora200gr
SAL KG
SAL MEDIO
ACEITE  220ML
ACEITE 430ML
ACEITE 500ML AGROIL
ACEITE 828ML AGROIL
VATEL 1/4
VATEL1/2
VATEL LTS
OTROS
OTROS
 salsa de tomate pequeña
salsa de tomate grande pamper
OTRAS 
OTRAS
MAYONESA PEQUE
MAYONESA MEDIANA
MAYONESA GRANDE
MAYONESA 1/2 PAMPA
MAYONESA 1/4 PAMPA
OTRAS 
OTRAS
MANTEQUILLA MAVESA 1/4
MANTEQUILLA 1/2 MAVESA
MANTEQUILLA 1/4 NELLY
MANTEQUILLA 1/2 NELLY
MANTEQUILLA 1/4 PAMPA
MANTEQUILLA 1/2 PAMPA
OTRAS
LA CAMPIÑA
LECHE 125GR DOBOM
LECHE KALY 400G
LECHE 125GR SAN SIMON
LECHE 400GR SANSIMON
LECHE 125GR M. FRESCA
LECHE 125GR UPACA
LECHE TETICA
LECHE LIQUIDA LTS
LECHE CONDESADA
leche dobon 200gr
CREMA DE ARROZ 225GR
CREMA DE ARROZ  AGUA B 400GR
CREMA DE ARROZ MARY
OTRAS
RICA CHICHA SOBRE
AVENA 200GR
AVENA 400GR
OTRAS
OTRAS
FORORO 250GR
FORORO 500GR
HARINA TRIGO 1/2 PAMPA
HARINA TRIGO KG PAMPA
HARINA TRIGO D.MAR
OTRAS 
OTRAS
ATUM BEEN
ATUM ROBISON
ATUM PACO
OTROS
SARDINA OMEGA T/A
SARDINA ALVARIGUA T/A/P
PASTA DE TOMATE pote
MAIZ LATA
MAIZ COTUFA
GUISANTES
PEPITONA
DIABLITOS
SALSA SOYA
SALSA INGLESA
SALSA AJO
COMBO DE SALSA
OSOLE SALSA PIZZA
OSOLE SALSA BOLOGNESA
OSOLE COMPOTA
COMPOTA VIDRIO
PICANTE FRIST
MEZCLAS FRIST
SOPA MAGGI
CUBITOS MAGGI
COMARICO
LAYLA SOBRE
TRIFOGON P
TRIFOGON CAJA
ALINO SOBRE
ALINO ARAUCA 90'GR
HUEVO C/U
HUEVO MEDIO CTTON
PANELA DULCE
BOKAS
GELATINA COMESTIBLE
VAINILLA P
VAINILLA G
SALSA DE TOMATE SOBRE
MAYONESA SOBRE
MOSTAZA SOBRE
MOSTAZA VIDRIO
BBQ SOBRE

SALSA ROSADA SOBRE
VINAGRE MANZANA
VINAGRE MAVESA P
VINAGRE CUSTODIA
VINAGRE MAVESA LTS
SALSA 57
OTROS
RIKESA
ABODO LA COMADRE POTE
ADOBO SOBRE COMADRE
CONDIMENTOS SOBRE
ESPECIES SOBRE
CARAOTA NEGRA
CARAOTA LENTEJAS
CARAOTA ARVEJA
CARAOTA QUINCHONCHO
FRUGYS 500ml
Frugys250ml
CARAOTA ROJA
JUGO PULP
JUGO JUSTIN/FRUTIS/FRUGGYS 1.5LTS
GATORADE
SPEEDMAX
AGUA MINERAL
MALTA RETORNABLE
MALTA DESECHABLE
MALTA 1.5LTS
REFRESCO PEPSI 2LTS
REFRESCO RETORNABLE 350ML
REFRESCO RETORNABLE 1.25LT
REFRESCO2LTS(FRIST,BIG,SUN,COOL)
REFRESCO 1,5LTS(PEPSI,GOLDEN)
COCACOLA LTS Y FANTA LTS
COCA COLA 1,5 Y FANTA 1,5LTS
COCA COLA Y FANTA 2LTS
GOLDEN LTS
SUN O COOL LTS
SUN O COOL BOMBITA
NATILLA
QUESO AMARRILLO
QUESO PAISA
JAMON
QUESO RES
MONTADELA KG
MORTADELA MEDIO
SALCHICHAS
SUERO
SURTIDOS
PAPA
PLATANO
TOMATE
CEBOLLA
AJO DE CABEZA
ZANAHORIA
PEPINO
CAMBUR
OTROS
POLLO ENTERO KG
POLLO PICADO KG
ALITAS KG
MUSLO KG
PECHUGA CON HUESO KG
PATA E HIGADO DE POLLO KG
CHULETA AHUMADA KG
HUESITOS KG
CHORIZO AHUMADO KG
CHULETA DE CERDO KG
MOLIDA KG 
BISTEC KG
OTRAS
MASA FACIL DE 400GR
MASA FACIL DE  800GR
TETAS CREMOSAS
TINITAS CREMOSAS
CHUPIS
TINA GRANDE

OTROS
PAN CANILLA
PAN FRANCES
PAN DE COCO
PAN DE GUAYABA
BOBOLONGO
PASTICA O MARMOLEADAS
PAN ANDINO
PAN DULCE
TOSTADAS
OTROS
OTROS
OTROS
JABON KH KILO
JABON KH MEDIO
JABON ALIVE KILO

JABON ALIVE 1/4
JABON HUGME KG
JABON BEBE KILO
JABON BEBE MEDIO
JABON BEBE 1/4
JABON NDERSA MEDIO
JABON DERSA 1/4
JABON LAS LLAVES MEDIO
CLORO MEDIO
SUAVITEL BOLSA PEQUENA
SUAVITEL GRANDE
FABULOSO BOLSA
AROMAX SOBRE
LAVAPLATOS BARRA AXION
LAVAPLATOS LIQUIDO POTE
JABON LIQUIDO
JABON POPULAR BARRA
JABON ESPECIAL BARRA
JABON LAS LLAVES BARRA 200GR
JABON LAS LLAVES FRESCA FRAGANCIA
JABON BANO LEMON
JABON BANO PERLA
JABON BANO PALMOLIVE
JABON BANO MEDICARE
JABON BANO DALAN
JABON BANO PROTEX
JABON ULTRACTIVO
JABON BARRA ALIVE
JABON BANO HARMONY
OTROS 
OTROS
OTROS
 PAPEL SANITARIO PEQ U/PQ
PAPEL SANITARIO GRAN U/PQ
PANALES PEQ
PANALES M
PANALES G
PANALES XG
SERVILLETA P
SERVILLETA G
PLATOS DESECHABLES
TENEDORES DESECHABLES
CUCHARAS DESECHABLES
VASOS DESECHABLES REFRESCO
VASOS DESECHABLES CAFE
BOLSAS DE 1/4 PQ
BOLSAS DE 1/2 PQ
BOLSAS DE KG PQ
BOLSAS 5KG PQ
TOALLAS HUMEDAS
TOALLAS SANITARIAS WUANITA DIA
TOALLAS SANITARIAS WUANITA NOCHE
TOALLAS SANITARIAS ALIVE DIA
TOALLAS SANITARIAS ALIVE NOCHE
TOALLAS SANITARIAS HUGME DIA
TOALLAS SANITARIAS HUGME NOCHE
TOALLAS SANITARIAS HUGME AZUL
PROTECTORES DIARIOS HUGME
DE
OTROS
OTROS
PAPEL ALUMINIO 6MTS
HISOPO G
HISOPO P
TARCO PAPA PIE
INCIENSO CONO
PLAGATOX
ESPONGA HIERRO
ESPONGA DOBLE USO
BRILLO JABONOSO
PEGA MOSCA
CREMA ALIDENT PQ
CREMA ALIDENT GD
CREMA COLGATE 
CEPILLO DENTAL 
CEPILLO DE BARREL
CEPILLO DE LAVAR SEDA SUAVE
CEPILLO DE LAVAR SEDA DURA
LAMPAZO
BOLSA DE BASURA NEGRA
GEL EGO SOBRE
GEL EGO POTE GD

FOSFORO
HOJILLAS DORCO
PRESTOBARBA DORDO 
PRESTOBARBA MAX3
BOLIGRAFOS PUNTA ACERO
BOLIGRAFOS KILOMETRO
BOMBILLOS NORMAL
BOMBILLOS AHORRADOR 15W
BOMBILLOS AHORRADOR 30W
BOMBILLOS AHORRADOR 45W
TEIPE
SOCATE
ENCHUFE (MACHO)
ENCHUFE(HEMBRA)
CARACOL ELECTRICO
TIRRAJES
PEGA RATON
ACEITE 3EN1
LAMPARAS LED 50W
LAMPARAS LED 100W
TEFLON
TOMACORRIENTE
PEGA TANQUE
PEGA LOCA COLO/ORIG
CREMA PARA ZAPATOS 
WIKI WIKI
HILO PARA COSER
AGUJAS PARA COSER
GANCHO PARA CABELLOS
GANCHOS PARA ROPA
MENTOL NORMAL
MENTOL CON CANABI
PILAS 2A/3A
COLADOR DE CAFE
CARGADORES DE TLF
CABLES USB

GLOBOS DE CARNAVALES
LIJAS DE AGUA
YESQUERO
TABACOS
VELAS
VELONES
VELON TAQUITOS
APAGADORES
DESODORANTE SOBRE
DESODORANTE POTECITO BALANCE
DESODORANTE POTECITO REXONA
CHAMPU DE SOBRE
ACONDICIONADOR SOBRE
ACONDICIONADOR POTE ALIVE
CHAMPU ALIVE 2EN1
CHAMPU DE POTE ALIVE ANTICASPA 350ML
CHAPU DE POTE HUGME 2EN1 400ML
SKALA POTE
CREMA PARA EL PELO HUGME P 200ML
CREMA PARA EL PELO HUGME G 750ML
CREMA PARA EL PELO HUGME M 200ML
Keramix tratamiento capilar
NUTRIBELA SOBRE
PANTENE TRATAMIENTO SOBRE
LISSO INTELIGENTE SOBRE
CRESPO INTELIGENTE SOBRE
TINTE SIGLO
TINTE HUGME
CIGARROS IBIZA
CIGARROS BERMONT
CIGARROS LANDUS
CIGARROS CONSUL
 
CIGARROS DIRECTOR
CIGARROS CAPI
CIGARROS MIAMI
CHIMU
PAPEL BOND
CARTULINA TIPO OFICIO
cartulina tipo carta 
HOJAS DE MAQUINA
HOJA DE EXAMEN
LAPIZ
BORRADOR
SACAPUNTA
REGLAS GEOMETRICAS
MARCADORES
RESALTADORES
CORRECTORES
PEGA EN BARRA
PEGA BLANCA ESCOLAR 40ML
PEGA BLANCA ESCOLAR 60ML
CARPETAS AMARILLAS
CARPETAS MARRONES
TIZAS BLANCA
TIZAS DE COLORES
PLASTILINAS PQ
PLASTILINAS M
PALITOS DE ALTURAS
PALETAS DE HELADOS
LIBRETAS NINO/NINA
BLOCK DE CONTRUCION
BLOCK LUSTRILLO
FOAMI NORMAL
FOAMI ESCARCHADO
SILICON LIQUIDO PQ
SILICON EN BARRA FINO
SILICON EN BARRA GRUESO
JUEGOS DIDACTICOS
SUSO
PAPEL CREPE
ESTANBRE
BOLSAS DE REGALOS GD
BOLSAS DE REGALOS PQ
COLORES
PINTURA AL FRIO
PORTA LAPIZ
RECOLECTOR DE HECES
RECOLECTOR DE ORINAS
ALCOHOL P
ALCOHOL G
ALGODON P/G
INYECTADORAS 3/5/10/20
CURITAS
VELITAS DE CUMPLEANOS

ACETONAS
PITA UNAS
BRILLO DE UNA
UÑAS

COMPACTO
PERFILADORES
PINZA DE CEJAS
PEGA PESTANAS
PERFUMES D/C
ESCARCHAS 
BALSAMO DE LABIOS
COLITAS 
LIGUITAS
PIOJITOS
GANCHETAS G/P
CORTA UNAS
VASELINA
OTROS
OTROS
CRAKEÑAS CLUB 
OTROS
GALLETAS TIP TOP
GALLETAS RELLENA
GALLETAS FESTIVAL
OREO
SALTITACOS
ARTENADOS
GLUP
CULB SOCIAL
HORNY BRANK
KRAKER BRANK
ESTRELLAS
COCO CRUNSH
GALLETAS MARIA
GALLETAS CHARMY
COCOSETTE
MAX COCO
TRULULU CHOCOCOLORES
TRULULU GOMITAS
TRULULU ARITOS
TRULULU FEROS
GOMITAS PLAY
GOMITAS GRISSY
TOSTON
TOM PQ
TOM MD
TOM GD
PIRUETAS PIRULIN
PIRUETAS FLIP
PIRUETAS PITICOS
PEPITO RIKO GD
PEPITORIKO PQ
RULITAS
PEPITO PUFFY GD
PEPITO PUFFY PQ
DORITOS GD
DORITOS PQ
RUFLES GD
RUFLES PQ
PAPITAS PUNH
PAPITAS PUNH ON
CHISTRIS GD
CHISTRIS PQ
CHISKESITO GD
CHISKESITO PQ
CHICHARRON GD
CHICHARRON PQ
TAKIS PICANTE
RAQUETIS
BOLICRONH
TOCINETAS GD
TOCINETAS PQ
RAPIDITOS GD
RAPIDITOS PQ
ROCKEE STAR
FLIP PQ
FLIP MD
FLIP GD
COTILLON PQ
GOMITAS GOMUCHO
GOMITAS FLORESTAL
AREQUIPE POTE
NUTELA POTE
GOMITAS ANGELITOS
GOMITAS TWITER
CARAMELO FRUTAS
CARAMELOS CHAOX2/ACIDOS/ETC
CHAO EN LINEA
CHAO TUBO
CHAO FRESH
CHOCOLATE ESTADIO
CHOCOLATE CRUNCHILATE
CHOCOLATE TORETTO
CHOCOLATE FLAQUITO
CHOCOLATE SAVOY
CHOCOLANTE BIANCHI
CHOCOLATE SAFARI
FREEGELL EN BARRA
HALF EN BARRA
TODDY 100GR
TODDY 200GR
OKA LOKA FUNSION
ANIPOP
CHOCOLISTO
CHUPETAS
CHICLE AGOGO
PEPITO ORIGINAL G
PEPITO ORIGINAL P
treloso 120g
Cumpleaños galleta

AROS DE PAPA
AZUCARADAS
MANI Y FRUTOS SECOS
MAIZENA 90GR
MAIZENA 200GR
CELOVEN papel
SAMBA`;

// Parse list
const items = rawList
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.length > 0)
    .map(line => line.toUpperCase())
    .filter(line => line !== 'OTRAS' && line !== 'OTROS');

console.log('Total items parsed:', items.length);

const insertProduct = db.prepare(`
    INSERT INTO products (barcode, name, sell_price, cost_price, stock)
    VALUES (?, ?, 0, 0, 0)
`);

let inserted = 0;
let skipped = 0;

db.transaction(() => {
    for (const item of items) {
        // Generate a random unique 6-character barcode
        const barcode = crypto.randomBytes(3).toString('hex').toUpperCase();
        try {
            insertProduct.run(barcode, item);
            inserted++;
        } catch (e) {
            console.error('Error on item:', item, e.message);
            skipped++;
        }
    }
})();

console.log(`Successfully inserted ${inserted} products.`);
if (skipped > 0) console.log(`Skipped ${skipped} products.`);
}

runImport().catch(console.error);
